const std = @import("std"); 


pub const Timezone = struct {
	id: []const u8
};



// Auto register timezones
fn create(key: []const u8) Timezone {
	const self = Timezone{ .id = key };
	return self;
}


// Timezones
pub const Africa = struct {
	pub const Abidjan = create("Africa/Abidjan");
	pub const Accra = create("Africa/Accra");
	pub const Addis_Ababa = create("Africa/Addis_Ababa");
	pub const Algiers = create("Africa/Algiers");
	pub const Asmara = create("Africa/Asmara");
	pub const Asmera = create("Africa/Asmera");
	pub const Bamako = create("Africa/Bamako");
	pub const Bangui = create("Africa/Bangui");
	pub const Banjul = create("Africa/Banjul");
	pub const Bissau = create("Africa/Bissau");
	pub const Blantyre = create("Africa/Blantyre");
	pub const Brazzaville = create("Africa/Brazzaville");
	pub const Bujumbura = create("Africa/Bujumbura");
	pub const Cairo = create("Africa/Cairo");
	pub const Casablanca = create("Africa/Casablanca");
	pub const Ceuta = create("Africa/Ceuta");
	pub const Conakry = create("Africa/Conakry");
	pub const Dakar = create("Africa/Dakar");
	pub const Dar_es_Salaam = create("Africa/Dar_es_Salaam");
	pub const Djibouti = create("Africa/Djibouti");
	pub const Douala = create("Africa/Douala");
	pub const El_Aaiun = create("Africa/El_Aaiun");
	pub const Freetown = create("Africa/Freetown");
	pub const Gaborone = create("Africa/Gaborone");
	pub const Harare = create("Africa/Harare");
	pub const Johannesburg = create("Africa/Johannesburg");
	pub const Juba = create("Africa/Juba");
	pub const Kampala = create("Africa/Kampala");
	pub const Khartoum = create("Africa/Khartoum");
	pub const Kigali = create("Africa/Kigali");
	pub const Kinshasa = create("Africa/Kinshasa");
	pub const Lagos = create("Africa/Lagos");
	pub const Libreville = create("Africa/Libreville");
	pub const Lome = create("Africa/Lome");
	pub const Luanda = create("Africa/Luanda");
	pub const Lubumbashi = create("Africa/Lubumbashi");
	pub const Lusaka = create("Africa/Lusaka");
	pub const Malabo = create("Africa/Malabo");
	pub const Maputo = create("Africa/Maputo");
	pub const Maseru = create("Africa/Maseru");
	pub const Mbabane = create("Africa/Mbabane");
	pub const Mogadishu = create("Africa/Mogadishu");
	pub const Monrovia = create("Africa/Monrovia");
	pub const Nairobi = create("Africa/Nairobi");
	pub const Ndjamena = create("Africa/Ndjamena");
	pub const Niamey = create("Africa/Niamey");
	pub const Nouakchott = create("Africa/Nouakchott");
	pub const Ouagadougou = create("Africa/Ouagadougou");
	pub const Porto_Novo = create("Africa/Porto-Novo");
	pub const Sao_Tome = create("Africa/Sao_Tome");
	pub const Timbuktu = create("Africa/Timbuktu");
	pub const Tripoli = create("Africa/Tripoli");
	pub const Tunis = create("Africa/Tunis");
	pub const Windhoek = create("Africa/Windhoek");
};
pub const America = struct {
	pub const Adak = create("America/Adak");
	pub const Anchorage = create("America/Anchorage");
	pub const Anguilla = create("America/Anguilla");
	pub const Antigua = create("America/Antigua");
	pub const Araguaina = create("America/Araguaina");
		pub const Argentina = struct {
			pub const Buenos_Aires = create("America/Argentina/Buenos_Aires");
			pub const Catamarca = create("America/Argentina/Catamarca");
			pub const ComodRivadavia = create("America/Argentina/ComodRivadavia");
			pub const Cordoba = create("America/Argentina/Cordoba");
			pub const Jujuy = create("America/Argentina/Jujuy");
			pub const La_Rioja = create("America/Argentina/La_Rioja");
			pub const Mendoza = create("America/Argentina/Mendoza");
			pub const Rio_Gallegos = create("America/Argentina/Rio_Gallegos");
			pub const Salta = create("America/Argentina/Salta");
			pub const San_Juan = create("America/Argentina/San_Juan");
			pub const San_Luis = create("America/Argentina/San_Luis");
			pub const Tucuman = create("America/Argentina/Tucuman");
			pub const Ushuaia = create("America/Argentina/Ushuaia");
		};
	pub const Aruba = create("America/Aruba");
	pub const Asuncion = create("America/Asuncion");
	pub const Atikokan = create("America/Atikokan");
	pub const Atka = create("America/Atka");
	pub const Bahia = create("America/Bahia");
	pub const Bahia_Banderas = create("America/Bahia_Banderas");
	pub const Barbados = create("America/Barbados");
	pub const Belem = create("America/Belem");
	pub const Belize = create("America/Belize");
	pub const Blanc_Sablon = create("America/Blanc-Sablon");
	pub const Boa_Vista = create("America/Boa_Vista");
	pub const Bogota = create("America/Bogota");
	pub const Boise = create("America/Boise");
	pub const Buenos_Aires = create("America/Buenos_Aires");
	pub const Cambridge_Bay = create("America/Cambridge_Bay");
	pub const Campo_Grande = create("America/Campo_Grande");
	pub const Cancun = create("America/Cancun");
	pub const Caracas = create("America/Caracas");
	pub const Catamarca = create("America/Catamarca");
	pub const Cayenne = create("America/Cayenne");
	pub const Cayman = create("America/Cayman");
	pub const Chicago = create("America/Chicago");
	pub const Chihuahua = create("America/Chihuahua");
	pub const Ciudad_Juarez = create("America/Ciudad_Juarez");
	pub const Coral_Harbour = create("America/Coral_Harbour");
	pub const Cordoba = create("America/Cordoba");
	pub const Costa_Rica = create("America/Costa_Rica");
	pub const Creston = create("America/Creston");
	pub const Cuiaba = create("America/Cuiaba");
	pub const Curacao = create("America/Curacao");
	pub const Danmarkshavn = create("America/Danmarkshavn");
	pub const Dawson = create("America/Dawson");
	pub const Dawson_Creek = create("America/Dawson_Creek");
	pub const Denver = create("America/Denver");
	pub const Detroit = create("America/Detroit");
	pub const Dominica = create("America/Dominica");
	pub const Edmonton = create("America/Edmonton");
	pub const Eirunepe = create("America/Eirunepe");
	pub const El_Salvador = create("America/El_Salvador");
	pub const Ensenada = create("America/Ensenada");
	pub const Fort_Nelson = create("America/Fort_Nelson");
	pub const Fort_Wayne = create("America/Fort_Wayne");
	pub const Fortaleza = create("America/Fortaleza");
	pub const Glace_Bay = create("America/Glace_Bay");
	pub const Godthab = create("America/Godthab");
	pub const Goose_Bay = create("America/Goose_Bay");
	pub const Grand_Turk = create("America/Grand_Turk");
	pub const Grenada = create("America/Grenada");
	pub const Guadeloupe = create("America/Guadeloupe");
	pub const Guatemala = create("America/Guatemala");
	pub const Guayaquil = create("America/Guayaquil");
	pub const Guyana = create("America/Guyana");
	pub const Halifax = create("America/Halifax");
	pub const Havana = create("America/Havana");
	pub const Hermosillo = create("America/Hermosillo");
		pub const Indiana = struct {
			pub const Indianapolis = create("America/Indiana/Indianapolis");
			pub const Knox = create("America/Indiana/Knox");
			pub const Marengo = create("America/Indiana/Marengo");
			pub const Petersburg = create("America/Indiana/Petersburg");
			pub const Tell_City = create("America/Indiana/Tell_City");
			pub const Vevay = create("America/Indiana/Vevay");
			pub const Vincennes = create("America/Indiana/Vincennes");
			pub const Winamac = create("America/Indiana/Winamac");
		};
	pub const Indianapolis = create("America/Indianapolis");
	pub const Inuvik = create("America/Inuvik");
	pub const Iqaluit = create("America/Iqaluit");
	pub const Jamaica = create("America/Jamaica");
	pub const Jujuy = create("America/Jujuy");
	pub const Juneau = create("America/Juneau");
		pub const Kentucky = struct {
			pub const Louisville = create("America/Kentucky/Louisville");
			pub const Monticello = create("America/Kentucky/Monticello");
		};
	pub const Knox_IN = create("America/Knox_IN");
	pub const Kralendijk = create("America/Kralendijk");
	pub const La_Paz = create("America/La_Paz");
	pub const Lima = create("America/Lima");
	pub const Los_Angeles = create("America/Los_Angeles");
	pub const Louisville = create("America/Louisville");
	pub const Lower_Princes = create("America/Lower_Princes");
	pub const Maceio = create("America/Maceio");
	pub const Managua = create("America/Managua");
	pub const Manaus = create("America/Manaus");
	pub const Marigot = create("America/Marigot");
	pub const Martinique = create("America/Martinique");
	pub const Matamoros = create("America/Matamoros");
	pub const Mazatlan = create("America/Mazatlan");
	pub const Mendoza = create("America/Mendoza");
	pub const Menominee = create("America/Menominee");
	pub const Merida = create("America/Merida");
	pub const Metlakatla = create("America/Metlakatla");
	pub const Mexico_City = create("America/Mexico_City");
	pub const Miquelon = create("America/Miquelon");
	pub const Moncton = create("America/Moncton");
	pub const Monterrey = create("America/Monterrey");
	pub const Montevideo = create("America/Montevideo");
	pub const Montreal = create("America/Montreal");
	pub const Montserrat = create("America/Montserrat");
	pub const Nassau = create("America/Nassau");
	pub const New_York = create("America/New_York");
	pub const Nipigon = create("America/Nipigon");
	pub const Nome = create("America/Nome");
	pub const Noronha = create("America/Noronha");
		pub const North_Dakota = struct {
			pub const Beulah = create("America/North_Dakota/Beulah");
			pub const Center = create("America/North_Dakota/Center");
			pub const New_Salem = create("America/North_Dakota/New_Salem");
		};
	pub const Nuuk = create("America/Nuuk");
	pub const Ojinaga = create("America/Ojinaga");
	pub const Panama = create("America/Panama");
	pub const Pangnirtung = create("America/Pangnirtung");
	pub const Paramaribo = create("America/Paramaribo");
	pub const Phoenix = create("America/Phoenix");
	pub const Port_au_Prince = create("America/Port-au-Prince");
	pub const Port_of_Spain = create("America/Port_of_Spain");
	pub const Porto_Acre = create("America/Porto_Acre");
	pub const Porto_Velho = create("America/Porto_Velho");
	pub const Puerto_Rico = create("America/Puerto_Rico");
	pub const Punta_Arenas = create("America/Punta_Arenas");
	pub const Rainy_River = create("America/Rainy_River");
	pub const Rankin_Inlet = create("America/Rankin_Inlet");
	pub const Recife = create("America/Recife");
	pub const Regina = create("America/Regina");
	pub const Resolute = create("America/Resolute");
	pub const Rio_Branco = create("America/Rio_Branco");
	pub const Rosario = create("America/Rosario");
	pub const Santa_Isabel = create("America/Santa_Isabel");
	pub const Santarem = create("America/Santarem");
	pub const Santiago = create("America/Santiago");
	pub const Santo_Domingo = create("America/Santo_Domingo");
	pub const Sao_Paulo = create("America/Sao_Paulo");
	pub const Scoresbysund = create("America/Scoresbysund");
	pub const Shiprock = create("America/Shiprock");
	pub const Sitka = create("America/Sitka");
	pub const St_Barthelemy = create("America/St_Barthelemy");
	pub const St_Johns = create("America/St_Johns");
	pub const St_Kitts = create("America/St_Kitts");
	pub const St_Lucia = create("America/St_Lucia");
	pub const St_Thomas = create("America/St_Thomas");
	pub const St_Vincent = create("America/St_Vincent");
	pub const Swift_Current = create("America/Swift_Current");
	pub const Tegucigalpa = create("America/Tegucigalpa");
	pub const Thule = create("America/Thule");
	pub const Thunder_Bay = create("America/Thunder_Bay");
	pub const Tijuana = create("America/Tijuana");
	pub const Toronto = create("America/Toronto");
	pub const Tortola = create("America/Tortola");
	pub const Vancouver = create("America/Vancouver");
	pub const Virgin = create("America/Virgin");
	pub const Whitehorse = create("America/Whitehorse");
	pub const Winnipeg = create("America/Winnipeg");
	pub const Yakutat = create("America/Yakutat");
	pub const Yellowknife = create("America/Yellowknife");
};
pub const Antarctica = struct {
	pub const Casey = create("Antarctica/Casey");
	pub const Davis = create("Antarctica/Davis");
	pub const DumontDUrville = create("Antarctica/DumontDUrville");
	pub const Macquarie = create("Antarctica/Macquarie");
	pub const Mawson = create("Antarctica/Mawson");
	pub const McMurdo = create("Antarctica/McMurdo");
	pub const Palmer = create("Antarctica/Palmer");
	pub const Rothera = create("Antarctica/Rothera");
	pub const South_Pole = create("Antarctica/South_Pole");
	pub const Syowa = create("Antarctica/Syowa");
	pub const Troll = create("Antarctica/Troll");
	pub const Vostok = create("Antarctica/Vostok");
};
pub const Arctic = struct {
	pub const Longyearbyen = create("Arctic/Longyearbyen");
};
pub const Asia = struct {
	pub const Aden = create("Asia/Aden");
	pub const Almaty = create("Asia/Almaty");
	pub const Amman = create("Asia/Amman");
	pub const Anadyr = create("Asia/Anadyr");
	pub const Aqtau = create("Asia/Aqtau");
	pub const Aqtobe = create("Asia/Aqtobe");
	pub const Ashgabat = create("Asia/Ashgabat");
	pub const Ashkhabad = create("Asia/Ashkhabad");
	pub const Atyrau = create("Asia/Atyrau");
	pub const Baghdad = create("Asia/Baghdad");
	pub const Bahrain = create("Asia/Bahrain");
	pub const Baku = create("Asia/Baku");
	pub const Bangkok = create("Asia/Bangkok");
	pub const Barnaul = create("Asia/Barnaul");
	pub const Beirut = create("Asia/Beirut");
	pub const Bishkek = create("Asia/Bishkek");
	pub const Brunei = create("Asia/Brunei");
	pub const Calcutta = create("Asia/Calcutta");
	pub const Chita = create("Asia/Chita");
	pub const Choibalsan = create("Asia/Choibalsan");
	pub const Chongqing = create("Asia/Chongqing");
	pub const Chungking = create("Asia/Chungking");
	pub const Colombo = create("Asia/Colombo");
	pub const Dacca = create("Asia/Dacca");
	pub const Damascus = create("Asia/Damascus");
	pub const Dhaka = create("Asia/Dhaka");
	pub const Dili = create("Asia/Dili");
	pub const Dubai = create("Asia/Dubai");
	pub const Dushanbe = create("Asia/Dushanbe");
	pub const Famagusta = create("Asia/Famagusta");
	pub const Gaza = create("Asia/Gaza");
	pub const Harbin = create("Asia/Harbin");
	pub const Hebron = create("Asia/Hebron");
	pub const Ho_Chi_Minh = create("Asia/Ho_Chi_Minh");
	pub const Hong_Kong = create("Asia/Hong_Kong");
	pub const Hovd = create("Asia/Hovd");
	pub const Irkutsk = create("Asia/Irkutsk");
	pub const Istanbul = create("Asia/Istanbul");
	pub const Jakarta = create("Asia/Jakarta");
	pub const Jayapura = create("Asia/Jayapura");
	pub const Jerusalem = create("Asia/Jerusalem");
	pub const Kabul = create("Asia/Kabul");
	pub const Kamchatka = create("Asia/Kamchatka");
	pub const Karachi = create("Asia/Karachi");
	pub const Kashgar = create("Asia/Kashgar");
	pub const Kathmandu = create("Asia/Kathmandu");
	pub const Katmandu = create("Asia/Katmandu");
	pub const Khandyga = create("Asia/Khandyga");
	pub const Kolkata = create("Asia/Kolkata");
	pub const Krasnoyarsk = create("Asia/Krasnoyarsk");
	pub const Kuala_Lumpur = create("Asia/Kuala_Lumpur");
	pub const Kuching = create("Asia/Kuching");
	pub const Kuwait = create("Asia/Kuwait");
	pub const Macao = create("Asia/Macao");
	pub const Macau = create("Asia/Macau");
	pub const Magadan = create("Asia/Magadan");
	pub const Makassar = create("Asia/Makassar");
	pub const Manila = create("Asia/Manila");
	pub const Muscat = create("Asia/Muscat");
	pub const Nicosia = create("Asia/Nicosia");
	pub const Novokuznetsk = create("Asia/Novokuznetsk");
	pub const Novosibirsk = create("Asia/Novosibirsk");
	pub const Omsk = create("Asia/Omsk");
	pub const Oral = create("Asia/Oral");
	pub const Phnom_Penh = create("Asia/Phnom_Penh");
	pub const Pontianak = create("Asia/Pontianak");
	pub const Pyongyang = create("Asia/Pyongyang");
	pub const Qatar = create("Asia/Qatar");
	pub const Qostanay = create("Asia/Qostanay");
	pub const Qyzylorda = create("Asia/Qyzylorda");
	pub const Rangoon = create("Asia/Rangoon");
	pub const Riyadh = create("Asia/Riyadh");
	pub const Saigon = create("Asia/Saigon");
	pub const Sakhalin = create("Asia/Sakhalin");
	pub const Samarkand = create("Asia/Samarkand");
	pub const Seoul = create("Asia/Seoul");
	pub const Shanghai = create("Asia/Shanghai");
	pub const Singapore = create("Asia/Singapore");
	pub const Srednekolymsk = create("Asia/Srednekolymsk");
	pub const Taipei = create("Asia/Taipei");
	pub const Tashkent = create("Asia/Tashkent");
	pub const Tbilisi = create("Asia/Tbilisi");
	pub const Tehran = create("Asia/Tehran");
	pub const Tel_Aviv = create("Asia/Tel_Aviv");
	pub const Thimbu = create("Asia/Thimbu");
	pub const Thimphu = create("Asia/Thimphu");
	pub const Tokyo = create("Asia/Tokyo");
	pub const Tomsk = create("Asia/Tomsk");
	pub const Ujung_Pandang = create("Asia/Ujung_Pandang");
	pub const Ulaanbaatar = create("Asia/Ulaanbaatar");
	pub const Ulan_Bator = create("Asia/Ulan_Bator");
	pub const Urumqi = create("Asia/Urumqi");
	pub const Ust_Nera = create("Asia/Ust-Nera");
	pub const Vientiane = create("Asia/Vientiane");
	pub const Vladivostok = create("Asia/Vladivostok");
	pub const Yakutsk = create("Asia/Yakutsk");
	pub const Yangon = create("Asia/Yangon");
	pub const Yekaterinburg = create("Asia/Yekaterinburg");
	pub const Yerevan = create("Asia/Yerevan");
};
pub const Atlantic = struct {
	pub const Azores = create("Atlantic/Azores");
	pub const Bermuda = create("Atlantic/Bermuda");
	pub const Canary = create("Atlantic/Canary");
	pub const Cape_Verde = create("Atlantic/Cape_Verde");
	pub const Faeroe = create("Atlantic/Faeroe");
	pub const Faroe = create("Atlantic/Faroe");
	pub const Jan_Mayen = create("Atlantic/Jan_Mayen");
	pub const Madeira = create("Atlantic/Madeira");
	pub const Reykjavik = create("Atlantic/Reykjavik");
	pub const South_Georgia = create("Atlantic/South_Georgia");
	pub const St_Helena = create("Atlantic/St_Helena");
	pub const Stanley = create("Atlantic/Stanley");
};
pub const Australia = struct {
	pub const ACT = create("Australia/ACT");
	pub const Adelaide = create("Australia/Adelaide");
	pub const Brisbane = create("Australia/Brisbane");
	pub const Broken_Hill = create("Australia/Broken_Hill");
	pub const Canberra = create("Australia/Canberra");
	pub const Currie = create("Australia/Currie");
	pub const Darwin = create("Australia/Darwin");
	pub const Eucla = create("Australia/Eucla");
	pub const Hobart = create("Australia/Hobart");
	pub const LHI = create("Australia/LHI");
	pub const Lindeman = create("Australia/Lindeman");
	pub const Lord_Howe = create("Australia/Lord_Howe");
	pub const Melbourne = create("Australia/Melbourne");
	pub const NSW = create("Australia/NSW");
	pub const North = create("Australia/North");
	pub const Perth = create("Australia/Perth");
	pub const Queensland = create("Australia/Queensland");
	pub const South = create("Australia/South");
	pub const Sydney = create("Australia/Sydney");
	pub const Tasmania = create("Australia/Tasmania");
	pub const Victoria = create("Australia/Victoria");
	pub const West = create("Australia/West");
	pub const Yancowinna = create("Australia/Yancowinna");
};
pub const Brazil = struct {
	pub const Acre = create("Brazil/Acre");
	pub const DeNoronha = create("Brazil/DeNoronha");
	pub const East = create("Brazil/East");
	pub const West = create("Brazil/West");
};
pub const CET = create("CET");
pub const CST6CDT = create("CST6CDT");
pub const Canada = struct {
	pub const Atlantic = create("Canada/Atlantic");
	pub const Central = create("Canada/Central");
	pub const Eastern = create("Canada/Eastern");
	pub const Mountain = create("Canada/Mountain");
	pub const Newfoundland = create("Canada/Newfoundland");
	pub const Pacific = create("Canada/Pacific");
	pub const Saskatchewan = create("Canada/Saskatchewan");
	pub const Yukon = create("Canada/Yukon");
};
pub const Chile = struct {
	pub const Continental = create("Chile/Continental");
	pub const EasterIsland = create("Chile/EasterIsland");
};
pub const Cuba = create("Cuba");
pub const EET = create("EET");
pub const EST = create("EST");
pub const EST5EDT = create("EST5EDT");
pub const Egypt = create("Egypt");
pub const Eire = create("Eire");
pub const Etc = struct {
	pub const GMT = create("Etc/GMT");
	pub const GMTp0 = create("Etc/GMT+0");
	pub const GMTp1 = create("Etc/GMT+1");
	pub const GMTp10 = create("Etc/GMT+10");
	pub const GMTp11 = create("Etc/GMT+11");
	pub const GMTp12 = create("Etc/GMT+12");
	pub const GMTp2 = create("Etc/GMT+2");
	pub const GMTp3 = create("Etc/GMT+3");
	pub const GMTp4 = create("Etc/GMT+4");
	pub const GMTp5 = create("Etc/GMT+5");
	pub const GMTp6 = create("Etc/GMT+6");
	pub const GMTp7 = create("Etc/GMT+7");
	pub const GMTp8 = create("Etc/GMT+8");
	pub const GMTp9 = create("Etc/GMT+9");
	pub const GMTm0 = create("Etc/GMT-0");
	pub const GMTm1 = create("Etc/GMT-1");
	pub const GMTm10 = create("Etc/GMT-10");
	pub const GMTm11 = create("Etc/GMT-11");
	pub const GMTm12 = create("Etc/GMT-12");
	pub const GMTm13 = create("Etc/GMT-13");
	pub const GMTm14 = create("Etc/GMT-14");
	pub const GMTm2 = create("Etc/GMT-2");
	pub const GMTm3 = create("Etc/GMT-3");
	pub const GMTm4 = create("Etc/GMT-4");
	pub const GMTm5 = create("Etc/GMT-5");
	pub const GMTm6 = create("Etc/GMT-6");
	pub const GMTm7 = create("Etc/GMT-7");
	pub const GMTm8 = create("Etc/GMT-8");
	pub const GMTm9 = create("Etc/GMT-9");
	pub const GMT0 = create("Etc/GMT0");
	pub const Greenwich = create("Etc/Greenwich");
	pub const UCT = create("Etc/UCT");
	pub const UTC = create("Etc/UTC");
	pub const Universal = create("Etc/Universal");
	pub const Zulu = create("Etc/Zulu");
};
pub const Europe = struct {
	pub const Amsterdam = create("Europe/Amsterdam");
	pub const Andorra = create("Europe/Andorra");
	pub const Astrakhan = create("Europe/Astrakhan");
	pub const Athens = create("Europe/Athens");
	pub const Belfast = create("Europe/Belfast");
	pub const Belgrade = create("Europe/Belgrade");
	pub const Berlin = create("Europe/Berlin");
	pub const Bratislava = create("Europe/Bratislava");
	pub const Brussels = create("Europe/Brussels");
	pub const Bucharest = create("Europe/Bucharest");
	pub const Budapest = create("Europe/Budapest");
	pub const Busingen = create("Europe/Busingen");
	pub const Chisinau = create("Europe/Chisinau");
	pub const Copenhagen = create("Europe/Copenhagen");
	pub const Dublin = create("Europe/Dublin");
	pub const Gibraltar = create("Europe/Gibraltar");
	pub const Guernsey = create("Europe/Guernsey");
	pub const Helsinki = create("Europe/Helsinki");
	pub const Isle_of_Man = create("Europe/Isle_of_Man");
	pub const Istanbul = create("Europe/Istanbul");
	pub const Jersey = create("Europe/Jersey");
	pub const Kaliningrad = create("Europe/Kaliningrad");
	pub const Kiev = create("Europe/Kiev");
	pub const Kirov = create("Europe/Kirov");
	pub const Kyiv = create("Europe/Kyiv");
	pub const Lisbon = create("Europe/Lisbon");
	pub const Ljubljana = create("Europe/Ljubljana");
	pub const London = create("Europe/London");
	pub const Luxembourg = create("Europe/Luxembourg");
	pub const Madrid = create("Europe/Madrid");
	pub const Malta = create("Europe/Malta");
	pub const Mariehamn = create("Europe/Mariehamn");
	pub const Minsk = create("Europe/Minsk");
	pub const Monaco = create("Europe/Monaco");
	pub const Moscow = create("Europe/Moscow");
	pub const Nicosia = create("Europe/Nicosia");
	pub const Oslo = create("Europe/Oslo");
	pub const Paris = create("Europe/Paris");
	pub const Podgorica = create("Europe/Podgorica");
	pub const Prague = create("Europe/Prague");
	pub const Riga = create("Europe/Riga");
	pub const Rome = create("Europe/Rome");
	pub const Samara = create("Europe/Samara");
	pub const San_Marino = create("Europe/San_Marino");
	pub const Sarajevo = create("Europe/Sarajevo");
	pub const Saratov = create("Europe/Saratov");
	pub const Simferopol = create("Europe/Simferopol");
	pub const Skopje = create("Europe/Skopje");
	pub const Sofia = create("Europe/Sofia");
	pub const Stockholm = create("Europe/Stockholm");
	pub const Tallinn = create("Europe/Tallinn");
	pub const Tirane = create("Europe/Tirane");
	pub const Tiraspol = create("Europe/Tiraspol");
	pub const Ulyanovsk = create("Europe/Ulyanovsk");
	pub const Uzhgorod = create("Europe/Uzhgorod");
	pub const Vaduz = create("Europe/Vaduz");
	pub const Vatican = create("Europe/Vatican");
	pub const Vienna = create("Europe/Vienna");
	pub const Vilnius = create("Europe/Vilnius");
	pub const Volgograd = create("Europe/Volgograd");
	pub const Warsaw = create("Europe/Warsaw");
	pub const Zagreb = create("Europe/Zagreb");
	pub const Zaporozhye = create("Europe/Zaporozhye");
	pub const Zurich = create("Europe/Zurich");
};
pub const Factory = create("Factory");
pub const GB = create("GB");
pub const GBmEire = create("GB-Eire");
pub const GMT = create("GMT");
pub const GMTp0 = create("GMT+0");
pub const GMTm0 = create("GMT-0");
pub const GMT0 = create("GMT0");
pub const Greenwich = create("Greenwich");
pub const HST = create("HST");
pub const Hongkong = create("Hongkong");
pub const Iceland = create("Iceland");
pub const Indian = struct {
	pub const Antananarivo = create("Indian/Antananarivo");
	pub const Chagos = create("Indian/Chagos");
	pub const Christmas = create("Indian/Christmas");
	pub const Cocos = create("Indian/Cocos");
	pub const Comoro = create("Indian/Comoro");
	pub const Kerguelen = create("Indian/Kerguelen");
	pub const Mahe = create("Indian/Mahe");
	pub const Maldives = create("Indian/Maldives");
	pub const Mauritius = create("Indian/Mauritius");
	pub const Mayotte = create("Indian/Mayotte");
	pub const Reunion = create("Indian/Reunion");
};
pub const Iran = create("Iran");
pub const Israel = create("Israel");
pub const Jamaica = create("Jamaica");
pub const Japan = create("Japan");
pub const Kwajalein = create("Kwajalein");
pub const Libya = create("Libya");
pub const MET = create("MET");
pub const MST = create("MST");
pub const MST7MDT = create("MST7MDT");
pub const Mexico = struct {
	pub const BajaNorte = create("Mexico/BajaNorte");
	pub const BajaSur = create("Mexico/BajaSur");
	pub const General = create("Mexico/General");
};
pub const NZ = create("NZ");
pub const NZmCHAT = create("NZ-CHAT");
pub const Navajo = create("Navajo");
pub const PRC = create("PRC");
pub const PST8PDT = create("PST8PDT");
pub const Pacific = struct {
	pub const Apia = create("Pacific/Apia");
	pub const Auckland = create("Pacific/Auckland");
	pub const Bougainville = create("Pacific/Bougainville");
	pub const Chatham = create("Pacific/Chatham");
	pub const Chuuk = create("Pacific/Chuuk");
	pub const Easter = create("Pacific/Easter");
	pub const Efate = create("Pacific/Efate");
	pub const Enderbury = create("Pacific/Enderbury");
	pub const Fakaofo = create("Pacific/Fakaofo");
	pub const Fiji = create("Pacific/Fiji");
	pub const Funafuti = create("Pacific/Funafuti");
	pub const Galapagos = create("Pacific/Galapagos");
	pub const Gambier = create("Pacific/Gambier");
	pub const Guadalcanal = create("Pacific/Guadalcanal");
	pub const Guam = create("Pacific/Guam");
	pub const Honolulu = create("Pacific/Honolulu");
	pub const Johnston = create("Pacific/Johnston");
	pub const Kanton = create("Pacific/Kanton");
	pub const Kiritimati = create("Pacific/Kiritimati");
	pub const Kosrae = create("Pacific/Kosrae");
	pub const Kwajalein = create("Pacific/Kwajalein");
	pub const Majuro = create("Pacific/Majuro");
	pub const Marquesas = create("Pacific/Marquesas");
	pub const Midway = create("Pacific/Midway");
	pub const Nauru = create("Pacific/Nauru");
	pub const Niue = create("Pacific/Niue");
	pub const Norfolk = create("Pacific/Norfolk");
	pub const Noumea = create("Pacific/Noumea");
	pub const Pago_Pago = create("Pacific/Pago_Pago");
	pub const Palau = create("Pacific/Palau");
	pub const Pitcairn = create("Pacific/Pitcairn");
	pub const Pohnpei = create("Pacific/Pohnpei");
	pub const Ponape = create("Pacific/Ponape");
	pub const Port_Moresby = create("Pacific/Port_Moresby");
	pub const Rarotonga = create("Pacific/Rarotonga");
	pub const Saipan = create("Pacific/Saipan");
	pub const Samoa = create("Pacific/Samoa");
	pub const Tahiti = create("Pacific/Tahiti");
	pub const Tarawa = create("Pacific/Tarawa");
	pub const Tongatapu = create("Pacific/Tongatapu");
	pub const Truk = create("Pacific/Truk");
	pub const Wake = create("Pacific/Wake");
	pub const Wallis = create("Pacific/Wallis");
	pub const Yap = create("Pacific/Yap");
};
pub const Poland = create("Poland");
pub const Portugal = create("Portugal");
pub const ROC = create("ROC");
pub const ROK = create("ROK");
pub const Singapore = create("Singapore");
pub const Turkey = create("Turkey");
pub const UCT = create("UCT");
pub const US = struct {
	pub const Alaska = create("US/Alaska");
	pub const Aleutian = create("US/Aleutian");
	pub const Arizona = create("US/Arizona");
	pub const Central = create("US/Central");
	pub const East_Indiana = create("US/East-Indiana");
	pub const Eastern = create("US/Eastern");
	pub const Hawaii = create("US/Hawaii");
	pub const Indiana_Starke = create("US/Indiana-Starke");
	pub const Michigan = create("US/Michigan");
	pub const Mountain = create("US/Mountain");
	pub const Pacific = create("US/Pacific");
	pub const Samoa = create("US/Samoa");
};
pub const UTC = create("UTC");
pub const Universal = create("Universal");
pub const WmSU = create("W-SU");
pub const WET = create("WET");
pub const Zulu = create("Zulu");


// Group Timezones
pub const lstgroup = std.ArrayList([] const u8).init(std.heap.page_allocator);

pub fn addGroup() void {
	lstgroup.append("Africa") catch unreachable;
	lstgroup.append("America") catch unreachable;
	lstgroup.append("Antarctica") catch unreachable;
	lstgroup.append("Arctic") catch unreachable;
	lstgroup.append("Asia") catch unreachable;
	lstgroup.append("Atlantic") catch unreachable;
	lstgroup.append("Australia") catch unreachable;
	lstgroup.append("Brazil") catch unreachable;
	lstgroup.append("Canada") catch unreachable;
	lstgroup.append("Chile") catch unreachable;
	lstgroup.append("Etc") catch unreachable;
	lstgroup.append("Europe") catch unreachable;
	lstgroup.append("Indian") catch unreachable;
	lstgroup.append("Mexico") catch unreachable;
	lstgroup.append("Pacific") catch unreachable;
	lstgroup.append("US") catch unreachable;
	lstgroup.append("base") catch unreachable;
}


// list Timezones
pub const Tzone = struct {
	group: []const u8,
	zone: []const u8
};



pub const lstTzone = std.ArrayList(Tzone).init(std.heap.page_allocator);

pub fn addTzone() void {
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Abidjan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Accra"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Addis_Ababa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Algiers"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Asmara"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Asmera"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Bamako"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Bangui"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Banjul"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Bissau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Blantyre"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Brazzaville"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Bujumbura"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Cairo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Casablanca"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Ceuta"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Conakry"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Dakar"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Dar_es_Salaam"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Djibouti"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Douala"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/El_Aaiun"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Freetown"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Gaborone"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Harare"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Johannesburg"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Juba"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Kampala"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Khartoum"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Kigali"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Kinshasa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Lagos"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Libreville"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Lome"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Luanda"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Lubumbashi"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Lusaka"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Malabo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Maputo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Maseru"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Mbabane"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Mogadishu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Monrovia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Nairobi"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Ndjamena"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Niamey"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Nouakchott"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Ouagadougou"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Porto-Novo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Sao_Tome"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Timbuktu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Tripoli"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Tunis"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Africa" ,.zone ="Africa/Windhoek"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Adak"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Anchorage"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Anguilla"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Antigua"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Araguaina"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Buenos_Aires"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Catamarca"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/ComodRivadavia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Cordoba"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Jujuy"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/La_Rioja"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Mendoza"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Rio_Gallegos"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Salta"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/San_Juan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/San_Luis"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Tucuman"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Argentina/Ushuaia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Aruba"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Asuncion"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Atikokan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Atka"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Bahia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Bahia_Banderas"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Barbados"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Belem"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Belize"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Blanc-Sablon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Boa_Vista"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Bogota"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Boise"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Buenos_Aires"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Cambridge_Bay"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Campo_Grande"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Cancun"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Caracas"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Catamarca"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Cayenne"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Cayman"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Chicago"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Chihuahua"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Ciudad_Juarez"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Coral_Harbour"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Cordoba"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Costa_Rica"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Creston"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Cuiaba"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Curacao"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Danmarkshavn"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Dawson"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Dawson_Creek"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Denver"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Detroit"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Dominica"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Edmonton"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Eirunepe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/El_Salvador"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Ensenada"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Fort_Nelson"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Fort_Wayne"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Fortaleza"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Glace_Bay"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Godthab"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Goose_Bay"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Grand_Turk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Grenada"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Guadeloupe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Guatemala"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Guayaquil"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Guyana"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Halifax"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Havana"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Hermosillo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Indianapolis"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Knox"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Marengo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Petersburg"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Tell_City"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Vevay"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Vincennes"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indiana/Winamac"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Indianapolis"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Inuvik"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Iqaluit"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Jamaica"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Jujuy"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Juneau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Kentucky/Louisville"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Kentucky/Monticello"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Knox_IN"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Kralendijk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/La_Paz"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Lima"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Los_Angeles"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Louisville"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Lower_Princes"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Maceio"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Managua"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Manaus"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Marigot"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Martinique"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Matamoros"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Mazatlan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Mendoza"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Menominee"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Merida"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Metlakatla"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Mexico_City"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Miquelon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Moncton"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Monterrey"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Montevideo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Montreal"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Montserrat"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Nassau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/New_York"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Nipigon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Nome"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Noronha"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/North_Dakota/Beulah"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/North_Dakota/Center"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/North_Dakota/New_Salem"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Nuuk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Ojinaga"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Panama"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Pangnirtung"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Paramaribo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Phoenix"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Port-au-Prince"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Port_of_Spain"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Porto_Acre"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Porto_Velho"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Puerto_Rico"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Punta_Arenas"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Rainy_River"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Rankin_Inlet"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Recife"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Regina"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Resolute"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Rio_Branco"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Rosario"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Santa_Isabel"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Santarem"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Santiago"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Santo_Domingo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Sao_Paulo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Scoresbysund"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Shiprock"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Sitka"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/St_Barthelemy"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/St_Johns"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/St_Kitts"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/St_Lucia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/St_Thomas"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/St_Vincent"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Swift_Current"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Tegucigalpa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Thule"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Thunder_Bay"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Tijuana"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Toronto"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Tortola"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Vancouver"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Virgin"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Whitehorse"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Winnipeg"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Yakutat"}) catch unreachable;
	lstTzone.append(Tzone{.group = "America" ,.zone ="America/Yellowknife"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Casey"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Davis"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/DumontDUrville"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Macquarie"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Mawson"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/McMurdo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Palmer"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Rothera"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/South_Pole"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Syowa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Troll"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Antarctica" ,.zone ="Antarctica/Vostok"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Arctic" ,.zone ="Arctic/Longyearbyen"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Aden"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Almaty"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Amman"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Anadyr"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Aqtau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Aqtobe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ashgabat"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ashkhabad"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Atyrau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Baghdad"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Bahrain"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Baku"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Bangkok"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Barnaul"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Beirut"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Bishkek"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Brunei"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Calcutta"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Chita"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Choibalsan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Chongqing"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Chungking"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Colombo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Dacca"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Damascus"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Dhaka"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Dili"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Dubai"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Dushanbe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Famagusta"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Gaza"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Harbin"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Hebron"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ho_Chi_Minh"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Hong_Kong"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Hovd"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Irkutsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Istanbul"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Jakarta"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Jayapura"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Jerusalem"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kabul"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kamchatka"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Karachi"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kashgar"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kathmandu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Katmandu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Khandyga"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kolkata"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Krasnoyarsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kuala_Lumpur"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kuching"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Kuwait"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Macao"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Macau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Magadan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Makassar"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Manila"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Muscat"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Nicosia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Novokuznetsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Novosibirsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Omsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Oral"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Phnom_Penh"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Pontianak"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Pyongyang"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Qatar"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Qostanay"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Qyzylorda"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Rangoon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Riyadh"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Saigon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Sakhalin"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Samarkand"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Seoul"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Shanghai"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Singapore"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Srednekolymsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Taipei"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Tashkent"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Tbilisi"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Tehran"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Tel_Aviv"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Thimbu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Thimphu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Tokyo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Tomsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ujung_Pandang"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ulaanbaatar"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ulan_Bator"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Urumqi"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Ust-Nera"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Vientiane"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Vladivostok"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Yakutsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Yangon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Yekaterinburg"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Asia" ,.zone ="Asia/Yerevan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Azores"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Bermuda"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Canary"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Cape_Verde"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Faeroe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Faroe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Jan_Mayen"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Madeira"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Reykjavik"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/South_Georgia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/St_Helena"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Atlantic" ,.zone ="Atlantic/Stanley"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/ACT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Adelaide"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Brisbane"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Broken_Hill"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Canberra"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Currie"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Darwin"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Eucla"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Hobart"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/LHI"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Lindeman"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Lord_Howe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Melbourne"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/NSW"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/North"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Perth"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Queensland"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/South"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Sydney"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Tasmania"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Victoria"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/West"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Australia" ,.zone ="Australia/Yancowinna"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Brazil" ,.zone ="Brazil/Acre"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Brazil" ,.zone ="Brazil/DeNoronha"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Brazil" ,.zone ="Brazil/East"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Brazil" ,.zone ="Brazil/West"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="CET"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="CST6CDT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Atlantic"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Central"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Eastern"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Mountain"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Newfoundland"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Pacific"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Saskatchewan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Canada" ,.zone ="Canada/Yukon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Chile" ,.zone ="Chile/Continental"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Chile" ,.zone ="Chile/EasterIsland"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Cuba"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="EET"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="EST"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="EST5EDT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Egypt"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Eire"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+0"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+1"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+10"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+11"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+12"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+2"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+3"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+4"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+5"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+6"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+7"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+8"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT+9"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-0"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-1"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-10"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-11"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-12"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-13"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-14"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-2"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-3"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-4"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-5"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-6"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-7"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-8"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT-9"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/GMT0"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/Greenwich"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/UCT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/UTC"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/Universal"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Etc" ,.zone ="Etc/Zulu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Amsterdam"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Andorra"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Astrakhan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Athens"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Belfast"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Belgrade"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Berlin"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Bratislava"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Brussels"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Bucharest"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Budapest"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Busingen"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Chisinau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Copenhagen"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Dublin"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Gibraltar"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Guernsey"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Helsinki"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Isle_of_Man"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Istanbul"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Jersey"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Kaliningrad"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Kiev"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Kirov"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Kyiv"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Lisbon"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Ljubljana"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/London"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Luxembourg"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Madrid"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Malta"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Mariehamn"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Minsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Monaco"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Moscow"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Nicosia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Oslo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Paris"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Podgorica"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Prague"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Riga"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Rome"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Samara"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/San_Marino"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Sarajevo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Saratov"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Simferopol"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Skopje"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Sofia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Stockholm"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Tallinn"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Tirane"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Tiraspol"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Ulyanovsk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Uzhgorod"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Vaduz"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Vatican"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Vienna"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Vilnius"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Volgograd"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Warsaw"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Zagreb"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Zaporozhye"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Europe" ,.zone ="Europe/Zurich"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Factory"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="GB"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="GB-Eire"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="GMT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="GMT+0"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="GMT-0"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="GMT0"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Greenwich"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="HST"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Hongkong"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Iceland"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Antananarivo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Chagos"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Christmas"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Cocos"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Comoro"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Kerguelen"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Mahe"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Maldives"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Mauritius"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Mayotte"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Indian" ,.zone ="Indian/Reunion"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Iran"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Israel"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Jamaica"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Japan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Kwajalein"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Libya"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="MET"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="MST"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="MST7MDT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Mexico" ,.zone ="Mexico/BajaNorte"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Mexico" ,.zone ="Mexico/BajaSur"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Mexico" ,.zone ="Mexico/General"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="NZ"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="NZ-CHAT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Navajo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="PRC"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="PST8PDT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Apia"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Auckland"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Bougainville"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Chatham"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Chuuk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Easter"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Efate"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Enderbury"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Fakaofo"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Fiji"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Funafuti"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Galapagos"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Gambier"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Guadalcanal"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Guam"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Honolulu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Johnston"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Kanton"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Kiritimati"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Kosrae"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Kwajalein"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Majuro"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Marquesas"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Midway"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Nauru"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Niue"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Norfolk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Noumea"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Pago_Pago"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Palau"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Pitcairn"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Pohnpei"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Ponape"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Port_Moresby"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Rarotonga"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Saipan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Samoa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Tahiti"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Tarawa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Tongatapu"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Truk"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Wake"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Wallis"}) catch unreachable;
	lstTzone.append(Tzone{.group = "Pacific" ,.zone ="Pacific/Yap"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Poland"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Portugal"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="ROC"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="ROK"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Singapore"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Turkey"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="UCT"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Alaska"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Aleutian"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Arizona"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Central"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/East-Indiana"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Eastern"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Hawaii"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Indiana-Starke"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Michigan"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Mountain"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Pacific"}) catch unreachable;
	lstTzone.append(Tzone{.group = "US" ,.zone ="US/Samoa"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="UTC"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Universal"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="W-SU"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="WET"}) catch unreachable;
	lstTzone.append(Tzone{.group = "base" ,.zone ="Zulu"}) catch unreachable;
}
