{
  "PANEL": [
    {
      "name": "Xpanel",
      "posx": 1,
      "posy": 1,
      "lines": 44,
      "cols": 168,
      "cadre": "line1",
      "title": "Test-Json",
      "button": [
        {
          "name": "F1",
          "key": "F1",
          "show": true,
          "check": false,
          "title": "Help"
        },
        {
          "name": "F3",
          "key": "F3",
          "show": true,
          "check": false,
          "title": "Exit"
        }
      ],
      "label": [
        {
          "name": "L39",
          "posx": 3,
          "posy": 9,
          "text": "Fiche",
          "title": true
        },
        {
          "name": "L59",
          "posx": 5,
          "posy": 9,
          "text": "Nom................:",
          "title": false
        },
        {
          "name": "L79",
          "posx": 7,
          "posy": 9,
          "text": "Prénom.............:",
          "title": false
        },
        {
          "name": "L480",
          "posx": 4,
          "posy": 80,
          "text": "text free            :",
          "title": false
        },
        {
          "name": "L680",
          "posx": 6,
          "posy": 80,
          "text": "text full            :",
          "title": false
        },
        {
          "name": "L880",
          "posx": 8,
          "posy": 80,
          "text": "Alpha                :",
          "title": false
        },
        {
          "name": "L1080",
          "posx": 10,
          "posy": 80,
          "text": "Alpha Upper          :",
          "title": false
        },
        {
          "name": "L1280",
          "posx": 12,
          "posy": 80,
          "text": "Alpha Numeric        :",
          "title": false
        },
        {
          "name": "L1480",
          "posx": 14,
          "posy": 80,
          "text": "Alpha Numeric Upper  :",
          "title": false
        },
        {
          "name": "L1680",
          "posx": 16,
          "posy": 80,
          "text": "Password             :",
          "title": false
        },
        {
          "name": "L1880",
          "posx": 18,
          "posy": 80,
          "text": "Yes/No               :",
          "title": false
        },
        {
          "name": "L2080",
          "posx": 20,
          "posy": 80,
          "text": "Udigit               :",
          "title": false
        },
        {
          "name": "L2280",
          "posx": 22,
          "posy": 80,
          "text": "Digit                :",
          "title": false
        },
        {
          "name": "L2480",
          "posx": 24,
          "posy": 80,
          "text": "Udecimal             :",
          "title": false
        },
        {
          "name": "L2680",
          "posx": 26,
          "posy": 80,
          "text": "Decimal              :",
          "title": false
        },
        {
          "name": "L2880",
          "posx": 28,
          "posy": 80,
          "text": "Date ISO             :",
          "title": false
        },
        {
          "name": "L3080",
          "posx": 30,
          "posy": 80,
          "text": "Date FR              :",
          "title": false
        },
        {
          "name": "L3280",
          "posx": 32,
          "posy": 80,
          "text": "Date US              :",
          "title": false
        },
        {
          "name": "L3480",
          "posx": 34,
          "posy": 80,
          "text": "Telephone            :",
          "title": false
        },
        {
          "name": "L3680",
          "posx": 36,
          "posy": 80,
          "text": "Mail ISO             :",
          "title": false
        },
        {
          "name": "L3880",
          "posx": 38,
          "posy": 80,
          "text": "Switch               :",
          "title": false
        },
        {
          "name": "L4080",
          "posx": 40,
          "posy": 80,
          "text": "Func                 :",
          "title": false
        }
      ],
      "field": [
        {
          "name": "NOM",
          "posx": 5,
          "posy": 30,
          "reftyp": "ALPHA_UPPER",
          "width": 30,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err NOM",
          "help": "help NOM",
          "procfunc": "",
          "proctask": "TNOM",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "PRENOM",
          "posx": 7,
          "posy": 30,
          "reftyp": "TEXT_FULL",
          "width": 30,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err PRENOM",
          "help": "help PRENOM",
          "procfunc": "",
          "proctask": "TPRENOM",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "FREE",
          "posx": 4,
          "posy": 103,
          "reftyp": "TEXT_FREE",
          "width": 30,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err FREE",
          "help": "help FREE",
          "procfunc": "",
          "proctask": "TFREE",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "FULL",
          "posx": 6,
          "posy": 103,
          "reftyp": "TEXT_FULL",
          "width": 32,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err FULL",
          "help": "help FUll",
          "procfunc": "",
          "proctask": "TFULL",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "ALPHA",
          "posx": 8,
          "posy": 103,
          "reftyp": "ALPHA",
          "width": 30,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err ALPHA",
          "help": "help ALHPA",
          "procfunc": "",
          "proctask": "TALPHA",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "ALPHAUPPER",
          "posx": 10,
          "posy": 103,
          "reftyp": "ALPHA_UPPER",
          "width": 20,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err ALPHAUPPER",
          "help": "help ALPHAUPPER",
          "procfunc": "",
          "proctask": "TALPHAUPPER",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "ALPHANUM",
          "posx": 12,
          "posy": 103,
          "reftyp": "ALPHA_NUMERIC",
          "width": 30,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err ALPHANUM",
          "help": "help ALPHANUM",
          "procfunc": "",
          "proctask": "TALPHANUM",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "ALPHAnumUPPER",
          "posx": 14,
          "posy": 103,
          "reftyp": "ALPHA_NUMERIC_UPPER",
          "width": 20,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err ALPHAnumUPPER",
          "help": "help ALPHAnumUPPER",
          "procfunc": "",
          "proctask": "TALPHAnumUPPER",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "PASSWORD",
          "posx": 16,
          "posy": 103,
          "reftyp": "PASSWORD",
          "width": 10,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err PASSWORD",
          "help": "help PASSWORD",
          "procfunc": "",
          "proctask": "TPASSWORD",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "YESNO",
          "posx": 18,
          "posy": 103,
          "reftyp": "YES_NO",
          "width": 1,
          "scal": 0,
          "text": "",
          "requier": false,
          "protect": false,
          "edtcar": "",
          "errmsg": "err YESNO",
          "help": "help YESNO",
          "procfunc": "",
          "proctask": "TYESNO",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "UDIGIT",
          "posx": 20,
          "posy": 103,
          "reftyp": "UDIGIT",
          "width": 10,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err UDIGIT",
          "help": "msg UDIGIT",
          "procfunc": "",
          "proctask": "TUDIGIT",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "DIGIT",
          "posx": 22,
          "posy": 103,
          "reftyp": "DIGIT",
          "width": 10,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err DIGIT",
          "help": "help DIGIT",
          "procfunc": "",
          "proctask": "TDIGIT",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "UDECIMAL",
          "posx": 24,
          "posy": 103,
          "reftyp": "UDECIMAL",
          "width": 15,
          "scal": 2,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err UDECIMAL",
          "help": "help UDECIMAL",
          "procfunc": "",
          "proctask": "TUDECIMAL",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "DECIMAL",
          "posx": 26,
          "posy": 103,
          "reftyp": "DECIMAL",
          "width": 15,
          "scal": 2,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err DECIMAL",
          "help": "help DECIMAL",
          "procfunc": "",
          "proctask": "TDECIMAL",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "DATEISO",
          "posx": 28,
          "posy": 103,
          "reftyp": "DATE_ISO",
          "width": 10,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err DATEISO",
          "help": "help DATEISO",
          "procfunc": "",
          "proctask": "TDATEISO",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "DATEFR",
          "posx": 30,
          "posy": 103,
          "reftyp": "DATE_FR",
          "width": 10,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err DATEFR",
          "help": "help DATEFR",
          "procfunc": "",
          "proctask": "TDATEFR",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "DATEUS",
          "posx": 32,
          "posy": 103,
          "reftyp": "DATE_US",
          "width": 10,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err DATEUS",
          "help": "help DATEUS",
          "procfunc": "",
          "proctask": "TDATEUS",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "TELEPHONE",
          "posx": 34,
          "posy": 103,
          "reftyp": "TELEPHONE",
          "width": 15,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": true,
          "edtcar": "",
          "errmsg": "err TELEPHONE",
          "help": "help TELEPHONE",
          "procfunc": "",
          "proctask": "TTELEPHONE",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "MAILISO",
          "posx": 36,
          "posy": 103,
          "reftyp": "MAIL_ISO",
          "width": 50,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": true,
          "edtcar": "",
          "errmsg": "err MAILISO",
          "help": "help MAILISO",
          "procfunc": "",
          "proctask": "TMAILISO",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "SWITCH",
          "posx": 38,
          "posy": 103,
          "reftyp": "SWITCH",
          "width": 1,
          "scal": 0,
          "text": "",
          "requier": false,
          "protect": false,
          "edtcar": "",
          "errmsg": "err SWITCH",
          "help": "help SWITCH",
          "procfunc": "",
          "proctask": "TSWITCH",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        },
        {
          "name": "FUNC",
          "posx": 40,
          "posy": 103,
          "reftyp": "FUNC",
          "width": 8,
          "scal": 0,
          "text": "",
          "requier": true,
          "protect": false,
          "edtcar": "",
          "errmsg": "err FUNC",
          "help": "help FUNC",
          "procfunc": "FFUNC",
          "proctask": "TFUNC",
          "progcall": "",
          "typecall": "",
          "parmcall": false,
          "regex": ""
        }
      ],
      "linev": [
        {
          "name": "V38",
          "posx": 3,
          "posy": 8,
          "lng": 4,
          "trace": "line1"
        },
        {
          "name": "V277",
          "posx": 2,
          "posy": 77,
          "lng": 39,
          "trace": "line1"
        }
      ],
      "lineh": [
        {
          "name": "H89",
          "posx": 8,
          "posy": 9,
          "lng": 51,
          "trace": "line1"
        },
        {
          "name": "H423",
          "posx": 42,
          "posy": 3,
          "lng": 164,
          "trace": "line1"
        }
      ]
    }
  ],
  "GRID": [
    {
      "name": "Gtable",
      "posx": 21,
      "posy": 8,
      "pagerows": 8,
      "separator": "│",
      "cadre": "line1",
      "cells": [
        {
          "text": "Voiture",
          "long": 20,
          "reftyp": "TEXT_FREE",
          "posy": 0,
          "edtcar": "",
          "atrcell": "fgGreen"
        },
        {
          "text": "Marque",
          "long": 20,
          "reftyp": "TEXT_FREE",
          "posy": 1,
          "edtcar": "",
          "atrcell": "fgYellow"
        },
        {
          "text": "Carburan",
          "long": 20,
          "reftyp": "TEXT_FREE",
          "posy": 2,
          "edtcar": "",
          "atrcell": "fgCyan"
        }
      ]
    },
    {
      "name": "CVoiture",
      "posx": 11,
      "posy": 8,
      "pagerows": 5,
      "separator": "│",
      "cadre": "line1",
      "cells": [
        {
          "text": "Voiture",
          "long": 20,
          "reftyp": "TEXT_FREE",
          "posy": 0,
          "edtcar": "",
          "atrcell": "fgGreen"
        }
      ]
    },
    {
      "name": "Cmarque",
      "posx": 13,
      "posy": 48,
      "pagerows": 10,
      "separator": "│",
      "cadre": "line1",
      "cells": [
        {
          "text": "Marque",
          "long": 20,
          "reftyp": "TEXT_FREE",
          "posy": 0,
          "edtcar": "",
          "atrcell": "fgGreen"
        }
      ]
    }
  ]
}
